// Generated from po/en.po by npm run translations. Edit the catalog instead.
export const english = Object.freeze({
  running_apps: "Running Apps",
  add_override_group: "Add override — %s",
  no_active_apps: "No active apps",
  no_active_apps_description: "Start an app with a tray indicator while the extension is enabled.",
  override_already_exists: "%s — Override already exists",
  labels: "Labels",
  labels_description: "Leave a label empty to use the app’s name.",
  ordering: "Ordering",
  ordering_description: "Lower numbers first. Default: 0. Ties keep registration order.",
  hide: "Hide",
  hide_description: "Apps in this list are hidden, even when they need attention.",
  apps: "Apps",
  add_override: "Add override",
  show_app_confirmation: "Show app?",
  delete_override_confirmation: "Delete override?",
  remove_hidden_app_confirmation: "Remove %s from the hidden apps list?",
  restore_default_confirmation: "Restore the default setting for %s?",
  cancel: "Cancel",
  delete: "Delete",
  no_overrides: "No overrides",
  no_overrides_description: "Add an override to choose an active app.",
  general: "General",
  appearance: "Appearance",
  appearance_description: "Configure the Running Apps menu",
  max_menu_height: "Maximum menu height",
  max_menu_height_description: "The menu becomes scrollable above this height",
  hide_passive_indicators: "Hide passive indicators",
  hide_passive_indicators_description:
    "Only show passive apps when they become active or need attention",
  default_app_name: "Default app name",
  label_for_app: "Label for %s",
  order_for_app: "Order for %s",
  edit_override_for_app: "Edit override for %s",
  confirm_changes_for_app: "Confirm changes for %s",
  discard_changes_for_app: "Discard changes for %s",
  delete_override_for_app: "Delete override for %s",
});
